#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          32
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a ~/CPP/ElectroDynamic/ElectroDynamic3D/a.out floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

#COLORS
bspc config normal_border_color "#777777"
bspc config focused_border_color "#ffff00"

#OPACITY
#bspc config normal_frame_opacity 0.2
#bspc config focused_frame_opacity 1.0


bspc config border_width        2
bspc config window_gap         	16
bspc config top_padding 	8

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt:"dpdwn" state=floating layer=above sticky=on border=off
bspc rule -a libreoffice state=tiled
bspc rule -a i3lock focus=on floating=on layer=above border=off
bspc rule -a /home/harwiltz/rust/rusty-snake/target/debug/rusty-snake focus=on floating=on layer=above
bspc rule -a "*:zathura" state=tiled
bspc rule -a Octave state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a "dzen2:*" layer=above manage=on
bspc rule -a "dzen:*" layer=above manage=on
