# -*- mode: snippet -*-
# name: TMLR Review 2025 
# key: r-tmlr25
# --

#+TITLE: [[file:paper.pdf][${1:TITLE}]]
#+SUBTITLE: Review of Paper${2:ID} for TMLR
#+STARTUP: overview
#+OPTIONS: toc:nil num:nil
$0
* TODO Summary of Contributions
#+BEGIN_COMMENT
Brief description, in the reviewer's words, of the contributions and
new knowledge presented by the submission (max 200000 characters). Add
formatting using Markdown and formulas using LaTeX. For more
information see https://openreview.net/faq.
#+END_COMMENT
* TODO Strengths and Weaknesses
#+BEGIN_COMMENT
List of the strong aspects of the submission as well as weaker
elements (if any) that you think require attention from the authors
(max 200000 characters). Add formatting using Markdown and formulas
using LaTeX. For more information see https://openreview.net/faq.
#+END_COMMENT
** Strengths
** Weaknesses
** Minor Issues
* TODO Requested Changes
#+BEGIN_COMMENT
List of proposed adjustments to the submission, specifying for each
whether they are critical to securing your recommendation for
acceptance or would simply strengthen the work in your view (max
200000 characters). Add formatting using Markdown and formulas using
LaTeX. For more information see https://openreview.net/faq.
#+END_COMMENT
* TODO Broader Impact Concerns
#+BEGIN_COMMENT
Brief description of any concerns on the ethical implications of the
work that would require adding a Broader Impact Statement (if one is
not present) or that are not sufficiently addressed in the Broader
Impact Statement section (if one is present) (max 200000
characters). Add formatting using Markdown and formulas using
LaTeX. For more information see https://openreview.net/faq.
#+END_COMMENT
* TODO Claims and Evidence
Are the claims made in the submission supported by accurate,
convincing and clear evidence? (see TMLR's evaluation criteria at
https://jmlr.org/tmlr/editorial-policies.html#evaluation).

- [ ] Yes
- [ ] No
* TODO Audience
Would at least some individuals in TMLR's audience be interested in
knowing the findings of this paper? (see TMLR's evaluation criteria at
https://jmlr.org/tmlr/editorial-policies.html#evaluation).

- [ ] Yes
- [ ] No
